#!/bin/bash

# Script to list all RSA SSH key pairs generated by generate_rsa_ssh_keypairs.sh
# Usage: ./list_rsa_ssh_keypairs.sh [base_ssh_dir]
# Default SSH directory is $HOME/.ssh

set -euo pipefail

error_exit() {
    echo "Error: $1" >&2
    exit 1
}

BASE_SSH_DIR="${1:-$HOME/.ssh}"

if [ ! -d "$BASE_SSH_DIR" ]; then
    error_exit "SSH directory '$BASE_SSH_DIR' does not exist."
fi

echo "Scanning for RSA SSH key pairs in: $BASE_SSH_DIR"
echo

found_any=0

mapfile -t ssh_dirs < <(find "$BASE_SSH_DIR" -mindepth 2 -maxdepth 2 -type d)

for sshdir in "${ssh_dirs[@]}"; do
    keyfile="$sshdir/key-pair/id_rsa"
    pubfile="$sshdir/key-pair/id_rsa.pub"

    if [ -f "$keyfile" ] && [ -f "$pubfile" ]; then
        found_any=1
        env_name=$(basename "$(dirname "$sshdir")")
        project_name=$(basename "$sshdir")

        echo "Environment: $env_name"
        echo "Project: $project_name"
        echo "SSH Key Directory: $sshdir/key-pair"
        echo "  Private Key: $keyfile"
        echo "  Public Key:  $pubfile"
        echo "----------------------------------------------------"
    fi
done

if [ "$found_any" -eq 0 ]; then
    echo "No RSA SSH key pairs found in $BASE_SSH_DIR."
fi