#!/bin/bash

# Script to list and optionally delete RSA SSH key pairs generated by generate_rsa_ssh_keypairs.sh
# Usage: ./manage_rsa_ssh_keypairs.sh [base_ssh_dir]
# Default SSH directory is $HOME/.ssh

set -euo pipefail

error_exit() {
    echo "Error: $1" >&2
    exit 1
}

BASE_SSH_DIR="${1:-$HOME/.ssh}"

if [ ! -d "$BASE_SSH_DIR" ]; then
    error_exit "SSH directory '$BASE_SSH_DIR' does not exist."
fi

list_keypairs() {
    local ssh_dirs=()
    mapfile -t ssh_dirs < <(find "$BASE_SSH_DIR" -mindepth 2 -maxdepth 2 -type d)
    local idx=1
    declare -gA keypair_map
    keypair_map=()

    echo "Scanning for RSA SSH key pairs in: $BASE_SSH_DIR"
    echo

    for sshdir in "${ssh_dirs[@]}"; do
        keyfile="$sshdir/key-pair/id_rsa"
        pubfile="$sshdir/key-pair/id_rsa.pub"

        if [ -f "$keyfile" ] && [ -f "$pubfile" ]; then
            env_name=$(basename "$(dirname "$sshdir")")
            project_name=$(basename "$sshdir")
            echo "$idx) Environment: $env_name"
            echo "   Project: $project_name"
            echo "   SSH Key Directory: $sshdir/key-pair"
            echo "     Private Key: $keyfile"
            echo "     Public Key:  $pubfile"
            echo "----------------------------------------------------"
            keypair_map["$idx"]="$sshdir"
            ((idx++))
        fi
    done

    if [ ${#keypair_map[@]} -eq 0 ]; then
        echo "No RSA SSH key pairs found in $BASE_SSH_DIR."
        return 1
    else
        return 0
    fi
}

delete_keypair() {
    local sshdir="$1"
    local keypair_dir="$sshdir/key-pair"
    read -p "Are you sure you want to delete all files in '$keypair_dir'? This CANNOT be undone. Type 'yes' to confirm: " confirm
    if [ "$confirm" != "yes" ]; then
        echo "Deletion cancelled for $keypair_dir."
        return
    fi
    rm -rf "$keypair_dir"
    echo "Deleted SSH key pair directory: $keypair_dir"

    # Clean up empty parent directories
    # Remove project directory if empty
    if [ -d "$sshdir" ] && [ -z "$(ls -A "$sshdir")" ]; then
        rmdir "$sshdir" && echo "Deleted empty project directory: $sshdir"
        # Remove env directory if empty
        envdir="$(dirname "$sshdir")"
        if [ -d "$envdir" ] && [ -z "$(ls -A "$envdir")" ]; then
            rmdir "$envdir" && echo "Deleted empty environment directory: $envdir"
        fi
    fi
}

while true; do
    if ! list_keypairs; then
        break
    fi

    echo "Enter the numbers of the key pairs you want to delete, separated by spaces (or press Enter to skip):"
    read -r input

    input=$(echo "$input" | xargs)

    if [ -z "$input" ]; then
        echo "No key pairs selected for deletion. Exiting."
        break
    fi

    for idx in $input; do
        sshdir="${keypair_map[$idx]:-}"
        if [ -z "$sshdir" ]; then
            echo "Invalid selection: $idx"
        else
            delete_keypair "$sshdir"
        fi
    done

    echo
    echo "Updated list of RSA SSH key pairs:"
    echo
done